### ISSUE TITLE
马上金融特征提取文件缺失

### ISSUE THREAD

**Issue by ranmelisssa** [chizhu/AI_Risk#1]
您好！我是一名在读学生，因为拜读并学习了您团队的关于这个赛题的解决方案，收益很大，十分感谢，但是您上传的关于马上金融的项目中关于特征提取部分没有上传完整（缺少文件feature_order_info_dealed.csv文件的生成部分）因为自己是新手，很希望能够完整学习下来，不知是不是因为不方便公开还是别的原因，所以想向您请教问一下。再次十分感谢您的开源，期待您的回复。谢谢！

**Comment by chizhu** [comment]
这部分是我队友生成  他当时也没整理好代码，所以只有零碎的loct那个相关代码。你要学习的话 仔细看看b榜的gen_feat.py特征提取的思路和方法。希望能帮助你

**Comment by ranmelisssa** [comment]
好嘞！没想到能很快收到你的回复，很感谢，祝你工作顺利！生活愉快！

**Comment by chizhu** [comment]
我也是学生  一起学习😊
