### ISSUE TITLE
特征工程的几个小问题

### ISSUE THREAD

**Issue by Lilhxr** [chizhu/AI_Risk#2]
看了您的ppt，有以下问题
您的意思是指缺失所在的列，没缺失的转为1，缺失的转为0，然后统计样本中0的个数，再除以用户信息表的总维度如何理解（用户信息的数据总数）？那么请问相除后，构造的评估用户资料完整度的特征有何作用？
问题2：尝试将身份信息和时间信息转化为可以**入模**的变量怎么实现？

**Comment by chizhu** [comment]
1.资料完整度一定程度反映用户的可信度
2.身份证信息可以提取前3位得到地区的特征
3.时间提取weekday，day,以及各类时间之间做差获得相对时间。具体你可以查看代码
